### ISSUE TITLE
How to include proto files from a jar?

### ISSUE THREAD

**Issue by RishuK** [os72/protoc-jar-maven-plugin#48] opened 2017-11-13 13:26 UTC
Hi, 

I am using a maven dependency in my project which contains some proto files. These proto files are being imported in my working project's .proto file. However, the imports do not work because it is only using proto files from src/main/resources. Now I cannot figure out how to include a jar as one of the input directories?

**Comment by os72** [comment] 2017-11-13 20:08
I think this is a duplicate of #19 
Would you be able to help with the implementation?

**Comment by os72** [comment] 2018-06-29 15:45
Dupe of #19

**Closed** 2018-06-29 15:46 UTC
Labels: duplicate, help wanted

**Comment by os72** [comment] 2018-07-01 17:32
Released protoc-jar-maven-plugin 3.6.0.1
